const shopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILUR: "FETCH_COLLECTIONS_FAILUR",
  SET_SHOP_DATA: "SET_SHOP_DATA"
};

export default shopActionTypes;
